dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: WQTFcU5+rj94apBPmCtzJdSoQOkAkXFvbPKnek7KPsbUasET3IERLzB/jhNWnWb9+w1jr2lUKyUjwlhdF7q4lcdjjns5N3vTb50reHem8MgiPdRog+fXe06dCBQlbxfq5csrxx7eUim53bzUQSFESKu4owLi3bVrwCj7V3w3Dp1igV7IMob0PK45OwjbPEtvEQmLXjB/EDVzn3Eg7BvHjHMsjsi9h7ShtD/ybPbEXoBR+GPf+HtvlFvpsWkWsJZGEP0ZgJhh0RwXsE4u+njgGK6kQnVkvjR4jzO2SUfzgZTAlY6+qAksfXUMG2E4wNLT8qp0wfzoK+fMmdu1NkZRyJuWOyOLJZwbYGsnw5+9iz1PtQDA7t1j8HFrcT61kslQ10qUp/ZE0wpuztjglSB9kjjMNHevYNabC0aDZJUpsl8Oo9XeDVmAMtD7mupyC7XVQReER2KH0OUB2bkChmDgZVpcDnaoTzv0/NokWPnNmxsbeAYl6KDqhMTz7qQV66h+yJJixVc+T+d1W8VfCfaCUk7tYRPahVJ46AggrlVjR5n4evZfM7vJkB9JLHATXS8OWCwtghlVNwD1x7upromaFvy9PIHraf8Xs7N5PzXPvFj3Hr4b3BD7JZPJxTEVIq83/A+R1/HgIS5KnLrqe6SeTha7EMmnc5w9rDmfrelPTzg=
  - secure: aSPUUvgjYARmDwtCo9bHxjM6Buv6GVLIqdSX/W3wbp30iGBXkIGcPQsQmfCrUNiH7Qbjca5eBNVXTQJhWP9LV1nywfb2IMOjw+94ACZ3PBnRPXtfGuv4YMqqNpMuDfp9hoYVLRzSFNY9ecNum2OHDiGu8EJV7Z4x3aAXJ6zB3JKb4tp2erAGhASRpG8E+ImK5uspR52qxw/ZuD4VL2jLs166dfjQjJi/nedVfywym8XsxqnawnILoOBUHkMxWRo+1hUvlamZ5ztEtie7bsXqctG5K5dAPPprNuIGXSAvffRITocsV2irDaU16u8MwkCcGkLbD4+eFUFj5m1KYmryfpUo9a6Sd+gbEhceNbZD5C7PKocTiCV28pjqK/lrQ3Knq8Sne/g3gkJn9U71tewKHTiiFPMY28uGeb8TtVvo65fKyNwVEmtaeJKw5BDZ1LsT1lT/hbGAASWXTerJS5X5C2MGU3YeaEC39/z5lWclNzJGgDnNLD2pKaQKbYN6Q4Wvj1B67ngImHwfnBYm5gH8Z9kCHeGMskbm8yVk8cbpkpWCoqz4DDQjImAVE2t6jjm/oPJG0vLpVFdjEp1kQPjQ5tIXGnXxkFOIKsOjuLJJAQPH981lK7i50+tlK6wYgwjnIrXpHdZMozXIYLSbVUh+zpR+/qZWWgphECpAN7fuR5Y=
  - secure: i6beMTSkFCTorvAH+aFrSyFrHebHzUVjWIIBqHPIl1pToZBIWgxUqGKTPvWd2N/m3RSvZ+zSzpFhlGfp0JRayu46e+jLBqkVNvRBxWKy8lVzbNyepOH5iUInBNxego9YJKlG0Ecz3OEGI1Fnj3JbaUjGXkI2eMRmZipD5ebqmSzhwU2prjFkpIphntZ1LdxZqH+gQxp7ethGOKAI7AEBWvEoTxykRtjdp3N/GpIYzlfl8XklnuIX9omOOQhfGe/UqjwA5XrfeXXIn/aMIKT8w681t0/eMjOCgZWuP1AXczxmQLlWNuEY8wWvjUib1bPWPcgQZGtiBqccKbBALFYGyY9pFeJPdaaxCXK3nUAZBTuJdH4P/ulDNMZI9CI5Sc9U8EkprMqqwdpbUY9HCztj7NjMRXtcP/v0vFQ4hNSrQFgTobOsPmDWiJxAxFXwPjp0WNNzpIqu+wPiU+yks6OTRHBilEqKqZ49/D4J5eDkexNSmoA2MqtAigqPBRaXKWl7cNpmSvxaq/yF2spiOkZhdpfYoAqNyI9kYMfyK912sxrfTyNPvYgTYkJ0dj4ZFc1BgUMbu8NEa9NLslpxrwLw0E5C0Q22PsxkAlsSq4T8s51K8x3+2lOSHSEJfzcpra1UgKxd1cl1JPVBtov8gDhU9BAKe8hb6b5uIzA3V6zRS+Q=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
